# Generated by Django 4.2.3 on 2023-07-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clerics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("description", models.TextField()),
                ("posted_at", models.DateTimeField()),
                (
                    "like_dislikes",
                    models.CharField(
                        choices=[("1", "Like"), ("0", "Dislike")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="clerics.clerics",
                    ),
                ),
            ],
        ),
    ]
