# Generated by Django 4.2.3 on 2023-07-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like_dislikes',
            field=models.CharField(choices=[('1', 'Like'), ('0', 'Dislike')], max_length=10, null=True),
        ),
    ]
