# Generated by Django 4.2.3 on 2023-07-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clerics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_author', models.CharField(blank=True, max_length=100)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('CONTENT CATEGORY REPORT', 'Report1'), ('CONTENT QUALITY REPORT', 'Report2'), ('USER GENERATED REPORT', 'Report3'), ('CONTENT FEEDBACK REPORT', 'Report4')], max_length=255)),
                ('why_report', models.TextField(blank=True, max_length=255)),
                ('report_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_to', to='clerics.clerics')),
            ],
        ),
    ]
