# Generated by Django 4.2.3 on 2023-07-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clerics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('profile_image', models.ImageField(upload_to='')),
                ('banner_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
